
'use client'
import React, { useState } from 'react';
import Link from 'next/link';
// Assuming getPortifolios is used elsewhere to fetch data, but not directly in this client component
// import getPortifolios from '../actions/getPortFolios'; 
import useIsMobile from '../hooks/isMobile';

// Import Draft.js components
import { CompositeDecorator, Editor, EditorState, ContentState, convertFromRaw } from "draft-js";
//import { svg } from 'leaflet';

// Helper function to get ContentState from item.description
// This function needs to be robust enough to handle both plain strings and Draft.js raw JSON strings.
// For the purpose of this component, we'll assume item.description is either a plain string
// or a JSON string representing Draft.js raw content.
const getTextFromEditor3 = (item: any): ContentState => {
  if (item && item.description) {
    try {
      // Attempt to parse as Draft.js raw content
      const rawContent = JSON.parse(item.description);
      // Check if it looks like Draft.js raw content (has blocks and entityMap)
      if (rawContent.blocks && Array.isArray(rawContent.blocks)) {
        return convertFromRaw(rawContent);
      }
    } catch (e) {
      // If parsing fails or it's not raw content, treat as plain text
      // console.warn("Description is not valid Draft.js raw content, treating as plain text:", e);
    }
    // Fallback: treat as plain text
    return ContentState.createFromText(item.description);
  }
  return ContentState.createFromText(''); // Return empty content if no description
};

// Define props for the Portfolio component
interface PortfolioProps {
  // Assuming portfolioItems is an array of objects with at least id, title, description, and viewCount (optional number)
  portfolioItems: any[]
}

const Portfolio: React.FC<PortfolioProps> = ({ portfolioItems }) => {
  const [compositeDecorator] = useState(new CompositeDecorator([]));
  const isMobile = useIsMobile();
  
  // Limit to only two jobs on mobile and four on desktop for the initial display
  const max_ = isMobile ? 2 : 4;
  const visiblePortifolios= portfolioItems.slice(0, max_);
  const hasMorPortifios = portfolioItems.length > max_; 
  
  return (
    <>
      <div className="my-4 py-4" id="portfolio">
        <h2 className="my-2 text-center text-3xl text-yellow-900 uppercase font-bold">
          Experience EEG&apos;s Innovative Projects That Shine
        </h2>
        <div className="flex justify-center">
          <div className="w-24 border-b-4 border-yellow-400 mb-8"></div>
        </div>

        <div className="px-4" data-aos="fade-down" data-aos-delay="600">
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {/* Iterate over portfolioItems and render each item */}
            {visiblePortifolios.map((item) => (
              <div
                key={item.id} // Use a unique key for each item, essential for React lists
                className="bg-white transition-all ease-in-out duration-400 overflow-hidden text-gray-700 hover:scale-105 rounded-lg shadow-2xl p-3 flex flex-col justify-between"
              >
                <div className="m-2 text-justify text-sm flex-grow flex flex-col">
                  <h4 className="font-semibold my-4 text-lg md:text-xl text-center mb-1 h-4">
                    {item.title}
                  </h4>
                  {/* Container for the Editor with fixed height and overflow hidden to limit content */}
                  <div className="relative h-32 overflow-hidden mb-4">
                    <Editor
                      // Create EditorState from the content generated by getTextFromEditor3
                      editorState={EditorState.createWithContent(getTextFromEditor3(item), compositeDecorator)}
                      readOnly // Ensure the editor is not editable
                      onChange={() => {}} // Dummy function for onChange, required by Draft.js Editor
                    />
                    {/* Gradient overlay to visually indicate truncated content */}
                    <div className="absolute bottom-0 left-0 right-0 h-10 bg-gradient-to-t from-white to-transparent"></div>
                  </div>

                  <div className="flex flex-col mt-auto"> {/* Use flex-col to stack button and view count */}
                    {/* NEW: View Count Display */}
                    {(item.viewCount > 0) && (
                      <div className="flex justify-end items-center text-xs text-gray-500 mb-2">
                        {/* Eye icon (View Icon) */}
                        <svg className="w-4 h-4 mr-1 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                        {item.viewCount} views
                      </div>
                    )}
                    
                    <Link
                      href={`/m/${item.id}`} // Link to a detail page for the full content
                      className="w-full inline-flex items-center justify-center px-6 py-3 bg-yellow-300 hover:bg-yellow-600 text-blue-700 rounded-md font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                    >
                      Learn More 
                      <svg
                        className="w-4 h-4 ml-2" // Increased left margin for better spacing
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fillRule="evenodd"
                          d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                          clipRule="evenodd"
                        ></path>
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {hasMorPortifios && (
          <div className="mt-12 text-center">
            <Link
              href="/projectslist"
              className="text-blue-600 hover:text-blue-800 font-semibold text-lg inline-flex items-center group"
            >
              View All Portifolios
              <svg
                className="w-5 h-5 ml-2 transition-transform duration-200 group-hover:translate-x-1"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 5l7 7-7 7"
                />
              </svg>
            </Link>
          </div>
        )}
      </div>
    </>
  );
};

export default Portfolio;

// 'use client'
// import React, { useState } from 'react';
// import Link from 'next/link';
// // Assuming getPortifolios is used elsewhere to fetch data, but not directly in this client component
// // import getPortifolios from '../actions/getPortFolios'; 
// import useIsMobile from '../hooks/isMobile';

// // Import Draft.js components
// import { CompositeDecorator, Editor, EditorState, ContentState, convertFromRaw } from "draft-js";

// // Helper function to get ContentState from item.description
// // This function needs to be robust enough to handle both plain strings and Draft.js raw JSON strings.
// // For the purpose of this component, we'll assume item.description is either a plain string
// // or a JSON string representing Draft.js raw content.
// const getTextFromEditor3 = (item: any): ContentState => {
//   if (item && item.description) {
//     try {
//       // Attempt to parse as Draft.js raw content
//       const rawContent = JSON.parse(item.description);
//       // Check if it looks like Draft.js raw content (has blocks and entityMap)
//       if (rawContent.blocks && Array.isArray(rawContent.blocks)) {
//         return convertFromRaw(rawContent);
//       }
//     } catch (e) {
//       // If parsing fails or it's not raw content, treat as plain text
//       // console.warn("Description is not valid Draft.js raw content, treating as plain text:", e);
//     }
//     // Fallback: treat as plain text
//     return ContentState.createFromText(item.description);
//   }
//   return ContentState.createFromText(''); // Return empty content if no description
// };

// // Define props for the Portfolio component
// interface PortfolioProps {
//   // Assuming portfolioItems is an array of objects with at least id, title, and description
//   portfolioItems: any[]
//   // Array<{
//   //   id: string;
//   //   title: string;
//   //   description: string; // Can be plain text or a JSON string of Draft.js raw content
//   //   // Add other properties if needed, e.g., imageSrc
//   // }>;
// }

// const Portfolio: React.FC<PortfolioProps> = ({ portfolioItems }) => {
//   // compositeDecorator is typically used for custom styling or linking within Draft.js content.
//   // For a read-only display without specific custom decorators, it might not be strictly necessary,
//   // but we keep it for consistency with the original code structure.
//   const [compositeDecorator] = useState(new CompositeDecorator([]));
//   const isMobile = useIsMobile();
//    // Limit to only two jobs on mobile and four on desktop for the initial display
//     const max_ = isMobile ? 2 : 4;
//     const visiblePortifolios= portfolioItems.slice(0, max_);
//     const hasMorPortifios = portfolioItems.length > max_; 
//   return (
//     <>
//       <div className="my-4 py-4" id="portfolio">
//         <h2 className="my-2 text-center text-3xl text-yellow-900 uppercase font-bold">
//           Experience EEG&apos;s Innovative Projects That Shine
//         </h2>
//         <div className="flex justify-center">
//           <div className="w-24 border-b-4 border-yellow-400 mb-8"></div>
//         </div>

//         <div className="px-4" data-aos="fade-down" data-aos-delay="600">
//           <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
//             {/* Iterate over portfolioItems and render each item */}
//             {visiblePortifolios.map((item) => (
//               <div
//                 key={item.id} // Use a unique key for each item, essential for React lists
//                 className="bg-white transition-all ease-in-out duration-400 overflow-hidden text-gray-700 hover:scale-105 rounded-lg shadow-2xl p-3 flex flex-col justify-between"
//               >
//                 <div className="m-2 text-justify text-sm flex-grow flex flex-col">
//                   <h4 className="font-semibold my-4 text-lg md:text-xl text-center mb-4 h-12">
//                     {item.title}
//                   </h4>
//                   {/* Container for the Editor with fixed height and overflow hidden to limit content */}
//                   <div className="relative h-32 overflow-hidden mb-4">
//                    <Editor
//                       // Create EditorState from the content generated by getTextFromEditor3
//                       editorState={EditorState.createWithContent(getTextFromEditor3(item), compositeDecorator)}
//                       readOnly // Ensure the editor is not editable
//                       onChange={() => {}} // Dummy function for onChange, required by Draft.js Editor
//                     />
//                     {/* Gradient overlay to visually indicate truncated content */}
//                     <div className="absolute bottom-0 left-0 right-0 h-10 bg-gradient-to-t from-white to-transparent"></div>
//                   </div>

//                   <div className="flex justify-center mt-auto"> {/* mt-auto pushes the button to the bottom */}
//                     <Link
//                       href={`/m/${item.id}`} // Link to a detail page for the full content
//                       className="w-full inline-flex items-center justify-center px-6 py-3 bg-yellow-300 hover:bg-yellow-600 text-blue-700 rounded-md font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
//                     >
//                       Learn More {/* Generic call to action for more details */}  item.viewCount>0 {item.viewCount}
//                       <svg
//                         className="w-4 h-4 ml-2" // Increased left margin for better spacing
//                         xmlns="http://www.w3.org/2000/svg"
//                         viewBox="0 0 20 20"
//                         fill="currentColor"
//                       >
//                         <path
//                           fillRule="evenodd"
//                           d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
//                           clipRule="evenodd"
//                         ></path>
//                       </svg>
//                     </Link>
//                   </div>
//                 </div>
//               </div>
//             ))}
//           </div>
//         </div>

//          {hasMorPortifios && (
//                             <div className="mt-12 text-center">
//                                 <Link
//                                     href="/projectslist"
//                                     className="text-blue-600 hover:text-blue-800 font-semibold text-lg inline-flex items-center group"
//                                 >
//                                     View All Portifolios
//                                     <svg
//                                         className="w-5 h-5 ml-2 transition-transform duration-200 group-hover:translate-x-1"
//                                         fill="none"
//                                         stroke="currentColor"
//                                         viewBox="0 0 24 24"
//                                         xmlns="http://www.w3.org/2000/svg"
//                                     >
//                                         <path
//                                             strokeLinecap="round"
//                                             strokeLinejoin="round"
//                                             strokeWidth={2}
//                                             d="M9 5l7 7-7 7"
//                                         />
//                                     </svg>
//                                 </Link>
//                             </div>
//                         )}
//       </div>
//     </>
//   );
// };

// export default Portfolio;